'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditRss

 '''<summary>
 '''pnlList control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlList As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''dlFeeds control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dlFeeds As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''cmdAdd control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdReturn control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''pnlEdit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''hidFeedId control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hidFeedId As Global.System.Web.UI.WebControls.HiddenField

 '''<summary>
 '''plFeedUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plFeedUrl As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtFeedUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtFeedUrl As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plCacheTime As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtCacheTime As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''valcompCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valcompCacheTime As Global.System.Web.UI.WebControls.CompareValidator

 '''<summary>
 '''reqCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents reqCacheTime As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''plUser control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plUser As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtUser control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtUser As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plPassword control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plPassword As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtPassword control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plOverrideTransform control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plOverrideTransform As Global.System.Web.UI.UserControl

 '''<summary>
 '''optStandard control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents optStandard As Global.System.Web.UI.WebControls.RadioButton

 '''<summary>
 '''ddOverrideTransform control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddOverrideTransform As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''optUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents optUrl As Global.System.Web.UI.WebControls.RadioButton

 '''<summary>
 '''optType control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents optType As Global.System.Web.UI.WebControls.RadioButton

 '''<summary>
 '''txtOverrideTransform control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtOverrideTransform As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''plCache control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plCache As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtCache control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtCache As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''cmdCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdUpdate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
