'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RssModule

 '''<summary>
 '''rssLine control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rssLine As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''pnlRss control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlRss As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''plhErrors control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents plhErrors As Global.System.Web.UI.WebControls.PlaceHolder

 '''<summary>
 '''btnUpdate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
End Class
