'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

  '''<summary>
  '''plDefaultCacheTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plDefaultCacheTime As Global.System.Web.UI.UserControl

  '''<summary>
  '''txtDefaultCacheTime control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDefaultCacheTime As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Comparevalidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Comparevalidator1 As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''Requiredfieldvalidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Requiredfieldvalidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''plRetryTimes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plRetryTimes As Global.System.Web.UI.UserControl

  '''<summary>
  '''txtRetryTimes control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtRetryTimes As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''plRetryTimeOut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plRetryTimeOut As Global.System.Web.UI.UserControl

  '''<summary>
  '''txtRetryTimeOut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtRetryTimeOut As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''plXslUrl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plXslUrl As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddXsl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddXsl As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''plItemsToShow control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plItemsToShow As Global.System.Web.UI.UserControl

  '''<summary>
  '''txtItemsToShow control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtItemsToShow As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Comparevalidator2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Comparevalidator2 As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''Requiredfieldvalidator2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Requiredfieldvalidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''plShowItemDetails control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plShowItemDetails As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowItemDetails control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowItemDetails As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''plShowItemDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plShowItemDate As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowItemDate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowItemDate As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''plTarget control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plTarget As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddTarget control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddTarget As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''plUseAjax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plUseAjax As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkUseAjax control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkUseAjax As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''plBackgroundDownload control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents plBackgroundDownload As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkBackgroundDownload control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkBackgroundDownload As Global.System.Web.UI.WebControls.CheckBox
End Class
